### ISSUE TITLE
Overlay - Width must be non-negative

### ISSUE THREAD

**Issue by iXab3r** [iXab3r/EyeAuras#23]
2019-11-14 16:10:30,035 [1 ] DEBUG [?.?] ScreenRegion selection result: Window: 0x00221032 (2232370) (title: logs) (class: CabinetWClass), Selection: {X=1588,Y=318,Width=939,Height=773}, Reason: OK
2019-11-14 16:10:30,035 [1 ] INFO  [?.?] Quick-Creating new tab using {"TriggerProperties":[],"OnEnterActionProperties":[],"Name":null,"WindowMatch":{"IsEmpty":false,"Title":"logs","IsRegex":false},"OverlayBounds":"1270.4000189304352,254.4000037908554,751.2000111937523,618.4000092148781","SourceRegionBounds":"1588,318,939,773","BorderThickness":0.0,"BorderColor":"#FFFAEBD7","IsClickThrough":false,"IsEnabled":true,"ThumbnailOpacity":1.0,"MaintainAspectRatio":true,"Version":1} args...
2019-11-14 16:10:30,035 [1 ] DEBUG [?.?] Adding new tab using config {"TriggerProperties":[],"OnEnterActionProperties":[],"Name":null,"WindowMatch":{"IsEmpty":false,"Title":"logs","IsRegex":false},"OverlayBounds":"1270.4000189304352,254.4000037908554,751.2000111937523,618.4000092148781","SourceRegionBounds":"1588,318,939,773","BorderThickness":0.0,"BorderColor":"#FFFAEBD7","IsClickThrough":false,"IsEnabled":true,"ThumbnailOpacity":1.0,"MaintainAspectRatio":true,"Version":1}...
2019-11-14 16:10:30,146 [1 ] INFO  [?.?] Overlay #EyeOverlayViewModel initialized
2019-11-14 16:10:30,151 [1 ] DEBUG [?.?] [ConfigChange] Detected Tabs list change
2019-11-14 16:10:30,152 [1 ] DEBUG [?.?] CreateNewTab operation took 116ms
2019-11-14 16:10:30,152 [1 ] WARN  [?.?] Failed to SetWindowLong to WS_EX_LTRREADING, WS_OVERLAPPED, WS_TILED, WS_EX_LEFT, WS_EX_TOOLWINDOW, WS_SYSMENU (previously WS_EX_RIGHTSCROLLBAR) of Window by HWND 0x00000000 (0)
2019-11-14 16:10:30,154 [1 ] DEBUG [?.?] Items order has changed, 
Old:
	"{\"TabName\":\"Aura #1\",\"DefaultTabName\":\"Aura #1\",\"IsSelected\":false,\"IsFlipped\":false}"
	"{\"TabName\":\"Aura #2\",\"DefaultTabName\":\"Aura #2\",\"IsSelected\":false,\"IsFlipped\":false}"
	"{\"TabName\":\"Aura #3\",\"DefaultTabName\":\"Aura #3\",\"IsSelected\":false,\"IsFlipped\":false}"
	"{\"TabName\":\"Aura #4\",\"DefaultTabName\":\"Aura #4\",\"IsSelected\":true,\"IsFlipped\":false}", 
New:
	"{\"TabName\":\"Aura #1\",\"DefaultTabName\":\"Aura #1\",\"IsSelected\":false,\"IsFlipped\":false}"
	"{\"TabName\":\"Aura #2\",\"DefaultTabName\":\"Aura #2\",\"IsSelected\":false,\"IsFlipped\":false}"
	"{\"TabName\":\"Aura #3\",\"DefaultTabName\":\"Aura #3\",\"IsSelected\":false,\"IsFlipped\":false}"
	"{\"TabName\":\"Aura #4\",\"DefaultTabName\":\"Aura #4\",\"IsSelected\":true,\"IsFlipped\":false}"
	"{\"TabName\":\"Aura #5\",\"DefaultTabName\":\"Aura #5\",\"IsSelected\":false,\"IsFlipped\":false}"
2019-11-14 16:10:30,155 [1 ] DEBUG [?.?] Source ordering:
	Source:  =>  =>  =>  => 
	View:  =>  =>  =>  => 
2019-11-14 16:10:30,171 [1 ] DEBUG [?.?] Selected tab: {"TabName":"Aura #5","DefaultTabName":"Aura #5","IsSelected":false,"IsFlipped":false}
2019-11-14 16:10:30,275 [1 ] DEBUG [?.?] Setting new Overlay Window(target: {"IsEmpty":false,"Title":"logs","IsRegex":false}): null => 0x00221032 (2232370) (title: logs) (class: CabinetWClass)
	{"Title":"logs","WindowBounds":"1587, 317, 943, 774","Class":"CabinetWClass","Handle":{"value":2232370},"ProcessId":10984,"ZOrder":71}
	{"Title":"logs","WindowBounds":"624, 86, 2199, 1158","Class":"CabinetWClass","Handle":{"value":4266936},"ProcessId":30632,"ZOrder":106}
	{"Title":"C:\\Users\\Xab3r\\AppData\\Roaming\\EyeAuras\\logs\\EyeAuras.Debug.2019-11-14.log - Sublime Text (UNREGISTERED)","WindowBounds":"-9, -9, 3363, 1458","Class":"PX_WINDOW_CLASS","Handle":{"value":7345172},"ProcessId":24724,"ZOrder":72}
2019-11-14 16:10:30,282 [1 ] WARN  [?.?] Failed to ShowWindow(0x00000000 (0)), error: NERR_Success
2019-11-14 16:10:30,458 [1 ] DEBUG [?.?] Resetting Thumbnail
2019-11-14 16:10:30,459 [1 ] DEBUG [?.?] Resetting Thumbnail
2019-11-14 16:10:30,497 [1 ] DEBUG [?.?] Resetting Thumbnail
2019-11-14 16:10:30,498 [1 ] DEBUG [?.?] Reconfiguring Thumbnail, targetWindow: 0x00221032 (2232370) (title: logs) (class: CabinetWClass) region: Region(1588,318,939,773)
2019-11-14 16:10:30,551 [1 ] ERROR [?.?] UI Exception occurred
System.ArgumentException: Width must be non-negative.
   at System.Windows.Rect.set_Width(Double value)
   at EyeAuras.OnTopReplica.ThumbnailRegion.ComputeRegion(Size sourceSize) in D:\Work\EyeAuras\Sources\EyeAuras.OnTopReplica\ThumbnailRegion.cs:line 95
   at EyeAuras.OnTopReplica.ThumbnailRegion.ComputeRegionSize(Size sourceSize) in D:\Work\EyeAuras\Sources\EyeAuras.OnTopReplica\ThumbnailRegion.cs:line 113
   at EyeAuras.UI.MainWindow.ThumbnailPanel.PrepareUpdateArgs() in D:\Work\EyeAuras\Sources\EyeAuras.UI\MainWindow\ThumbnailPanel.cs:line 265
   at PoeShared.Scaffolding.ObservableExtensions.<>c__DisplayClass4_0`2.<Select>b__0(T _) in D:\Work\EyeAuras\Sources\PoeShared.Core\Scaffolding\ObservableExtensions.cs:line 35
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 39
2019-11-14 16:10:30,563 [1 ] ERROR [?.?] UI Exception occurred
System.ArgumentException: Width must be non-negative.
   at System.Windows.Rect.set_Width(Double value)
   at EyeAuras.OnTopReplica.ThumbnailRegion.ComputeRegion(Size sourceSize) in D:\Work\EyeAuras\Sources\EyeAuras.OnTopReplica\ThumbnailRegion.cs:line 95
   at EyeAuras.OnTopReplica.ThumbnailRegion.ComputeRegionSize(Size sourceSize) in D:\Work\EyeAuras\Sources\EyeAuras.OnTopReplica\ThumbnailRegion.cs:line 113
   at EyeAuras.UI.MainWindow.ThumbnailPanel.PrepareUpdateArgs() in D:\Work\EyeAuras\Sources\EyeAuras.UI\MainWindow\ThumbnailPanel.cs:line 265
   at PoeShared.Scaffolding.ObservableExtensions.<>c__DisplayClass4_0`2.<Select>b__0(T _) in D:\Work\EyeAuras\Sources\PoeShared.Core\Scaffolding\ObservableExtensions.cs:line 35
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 39
2019-11-14 16:10:33,776 [24] DEBUG [?.?] Saving config (provider: PoeShared.Modularity.GenericConfigProvider`1[EyeAuras.UI.Prism.Modularity.EyeAurasConfig])...

**Comment by iXab3r** [comment]
fixed
