### ISSUE TITLE
DN Lib parsing error

### ISSUE THREAD

**Issue by iXab3r** [iXab3r/EyeAuras#28]
System.BadImageFormatException: .NET data directory RVA is 0
   at dnlib.DotNet.MD.MetadataFactory.Create(IPEImage peImage, CLRRuntimeReaderKind runtime, Boolean verify)
   at dnlib.DotNet.MD.MetadataFactory.Load(IPEImage peImage, CLRRuntimeReaderKind runtime)
   at dnlib.DotNet.MD.MetadataFactory.Load(String fileName, CLRRuntimeReaderKind runtime)
   at dnlib.DotNet.ModuleDefMD.Load(String fileName, ModuleCreationOptions options)
   at dnlib.DotNet.ModuleDefMD.Load(String fileName, ModuleContext context)
   at EyeAuras.UI.Prism.Modularity.DirectoryModuleCatalog.<>c.<LoadModuleCatalog>b__6_5(<>f__AnonymousType19`2 <>h__TransparentIdentifier1) in D:\Work\EyeAuras\Sources\EyeAuras.UI\Prism\Modularity\DirectoryModuleCatalog.cs:line 70
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at EyeAuras.UI.Prism.Modularity.DirectoryModuleCatalog.LoadModuleCatalog() in D:\Work\EyeAuras\Sources\EyeAuras.UI\Prism\Modularity\DirectoryModuleCatalog.cs:line 63
   at EyeAuras.UI.Prism.Modularity.DirectoryModuleCatalog.InnerLoad() in D:\Work\EyeAuras\Sources\EyeAuras.UI\Prism\Modularity\DirectoryModuleCatalog.cs:line 36
   at Prism.Modularity.ModuleCatalogBase.Load()
   at Prism.Modularity.ModuleCatalogBase.Initialize()
   at Prism.Modularity.ModuleManager.Run()
   at Prism.Unity.UnityBootstrapper.InitializeModules()
   at Prism.Unity.UnityBootstrapper.Run(Boolean runWithDefaultConfiguration)
   at EyeAuras.UI.Prism.EyeAurasBootstrapper.Run(Boolean runWithDefaultConfiguration) in D:\Work\EyeAuras\Sources\EyeAuras.UI\Prism\EyeAurasBootstrapper.cs:line 110
   at Prism.Bootstrapper.Run()
   at EyeAuras.UI.App.OnStartup(StartupEventArgs e) in D:\Work\EyeAuras\Sources\EyeAuras.UI\App.xaml.cs:line 149
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by iXab3r** [comment]
fixed
